### ISSUE TITLE
Needed iOS version

### ISSUE THREAD

**Issue by faizan-19** [shirsh94/flutter_doc_scanner#13]
Hi, thanks for the efforts for android when we will be able to scan on iOS?

**Comment by shirsh94** [comment]
This also works for iOS,  for more details just check the readme file for the iOS configuration setup.

**Comment by faizan-19** [comment]
it just shows only available for android on pressing scan

**Comment by shirsh94** [comment]
yes getScanDocumentsUri() is available for only android, but the main function which is getScanDocuments() this available for both iOS and Android.

**Comment by faizan-19** [comment]
but how can you scan the document then?
