### ISSUE TITLE
Scan does'nt work

### ISSUE THREAD

**Issue by Just2sire** [shirsh94/flutter_doc_scanner#17]
Even the simple scan doesn't work. Instead, i have the following error:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getScanDocumentsUri on channel flutter_doc_scanner)
E/flutter ( 9224): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter ( 9224): <asynchronous suspension>
E/flutter ( 9224): #1      MethodChannelFlutterDocScanner.getScanDocumentsUri (package:flutter_doc_scanner/flutter_doc_scanner_method_channel.dart:28:9)
E/flutter ( 9224): <asynchronous suspension>
E/flutter ( 9224): #2      _FlutterDocScannerScreenState.scanDocumentUri (package:mrz_scan/screens/flutter_doc_scanner/flutter_doc_scanner_screen.dart:33:26)
E/flutter ( 9224): <asynchronous suspension>

**Comment by shirsh94** [comment]
Please check example,it's properly working

**Comment by bhanitgaurav** [comment]
Fixed this. @shirsh94 in https://github.com/shirsh94/flutter_doc_scanner/pull/71
