### ISSUE TITLE
Getting an error from Play service while clicking on the Start scanning.

### ISSUE THREAD

**Issue by Maneesh-kp** [shirsh94/flutter_doc_scanner#18]
I am using Samsung Galaxy A13 and Galaxy A51 and on clicking of start scanning button I am getting an error page from the Play service saying "something went wrong" "Please try again" I tried below things but still not worked

1. Approved all permissions.
2. Added the permission in AndroidManifest also.
3. Cleared cashe.
4. Updated the Play service version.
5. Have stavle internet connection more than 24MBPS.
![Screenshot_20240724_122044_Google Play services](https://github.com/user-attachments/assets/e8df5f98-8c2c-4505-9c7b-3eb1c55af648)

But no luck. can someone please help me in resolving this issue?

**Comment by shirsh94** [comment]
Hi, thanks for bringing this up. It seems the issue might not be related to the flutter_doc_scanner library itself. Please check if there are any configuration or setup issues on your end. If you need further assistance, feel free to share more details about your setup and the issue you’re encountering.
