### ISSUE TITLE
Not working on web 

### ISSUE THREAD

**Issue by alikhan1999** [shirsh94/flutter_doc_scanner#19]
when I press the button of scan document . it came this error . I am using mac book pro intel chip. and run flutter web on both safari and chrome, same error occurred .

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

**Comment by shirsh94** [comment]
Currently, this supports only Android and ios.
