### ISSUE TITLE
How to change PDF to JPEG 

### ISSUE THREAD

**Issue by ASDdgomez** [shirsh94/flutter_doc_scanner#2]
Hi,

In the specifications it says that a PDF or a JPEG is generated, how can I change that format,
When generating in PDF some images load white spaces.
Thanks

**Comment by shirsh94** [comment]
Thank you for bringing this to our attention. I'm happy to let you know that the issue regarding the generation of PDFs and JPEGs has been resolved in version 0.0.2 of the plugin. Please update to the latest version to enjoy the fix.

If you encounter any further issues or have any other feedback, please don't hesitate to let us know.

Thanks again for your support and understanding.
