### ISSUE TITLE
get image

### ISSUE THREAD

**Issue by NassimCodeDev** [shirsh94/flutter_doc_scanner#20]
how to get image when run auto capture to store it in arrary

**Comment by shirsh94** [comment]
To store images in an array when auto capture runs, initialize a list and use the onCapture callback. Example:


```
List<File> capturedImages = [];

void _onImageCaptured(File image) {
  setState(() {
    capturedImages.add(image);
  });
}

@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(title: Text('Doc Scanner')),
    body: Column(
      children: [
        Expanded(
          child: FlutterDocScanner(
            autoCapture: true,
            onCapture: _onImageCaptured,
          ),
        ),
        Expanded(
          child: ListView.builder(
            itemCount: capturedImages.length,
            itemBuilder: (context, index) => Image.file(capturedImages[index]),
          ),
        ),
      ],
    ),
  );
}
```
This stores captured images in captured images and displays them in a list.

**Comment by NassimCodeDev** [comment]
i get this error firend error: The argument type 'FlutterDocScanner' can't be assigned to the parameter type 'Widget'.  (argument_type_not_assignable at [tscanner] lib\ui\screens\document_scanner_screen.dart:183)
error: The named parameter 'autoCapture' isn't defined. (undefined_named_parameter at [tscanner] lib\ui\screens\document_scanner_screen.dart:184)
error: The named parameter 'onCapture' isn't defined. (undefined_named_parameter at [tscanner] lib\ui\screens\document_scanner_screen.dart:185)
