### ISSUE TITLE
Not working on web!!!

### ISSUE THREAD

**Issue by AleCarda22** [shirsh94/flutter_doc_scanner#27]
On pub.dev you marked the package as working on web, so i said: finally a document scanner with Google ML Kit that works also on web. The problem is that it only works on IOS and Android...

**Comment by shirsh94** [comment]
Please check on the latest version, I added web support as well.

**Comment by shirsh94** [comment]
Unfortunately, web support for this library has been removed for certain reasons. If you’re looking for a solution to use this functionality on the web, I recommend switching to [flutter_doc_scanner_web](https://pub.dev/packages/flutter_doc_scanner_web), which is specifically designed to provide web support. Feel free to check it out and let us know if you encounter any issues!
