### ISSUE TITLE
Supported file types

### ISSUE THREAD

**Issue by bbeckley** [shirsh94/flutter_doc_scanner#29]
On the documentation it says that there is support for sending digitized files in PDF and JPEG formats back to your app.  I don't see how to configure that.  On Android it seems like everything is returned as a PDF and on iOS seems like I get pack a PNG.  Is there a way to change that ?

Thanks

**Comment by shirsh94** [comment]
yeah for Android it supports PDF and URI and for iOS it support JPEG,  you can convert it after fetch according to your requirement.
