### ISSUE TITLE
Swift Compiler Error (Xcode)

### ISSUE THREAD

**Issue by ASDdgomez** [shirsh94/flutter_doc_scanner#4]
Hi, 
in iOS i have this error
![image](https://github.com/shirsh94/flutter_doc_scanner/assets/103059856/c61aef7b-faa8-4efc-a8c6-aac32afd75d7)
Podffile
![image](https://github.com/shirsh94/flutter_doc_scanner/assets/103059856/96c3331b-5126-4816-b79f-fa64df19fc5a)
iOS Deployment
![image](https://github.com/shirsh94/flutter_doc_scanner/assets/103059856/d7c8868c-5b30-4b44-b736-0ec7750eb4a3)

Later

![image](https://github.com/shirsh94/flutter_doc_scanner/assets/103059856/628e21b2-9601-4002-903a-20ed16bed279)

Xcode Error

and later 

![image](https://github.com/shirsh94/flutter_doc_scanner/assets/103059856/612296b4-4755-4d40-9588-bfe7d465f001)

**Comment by shirsh94** [comment]
I've made significant changes to the iOS code in version 0.0.5. Can you please review and confirm?

**Comment by ASDdgomez** [comment]
Hi,
The app is done,
but when I take the photo:
![image](https://github.com/shirsh94/flutter_doc_scanner/assets/103059856/9d941099-ebd7-4252-9b01-e877645d8463)

**Comment by shirsh94** [comment]
Is it related to document scanner or not? If yes, then please clarify which points are not working:

1) Document scan in iOS with camera scanning and dynamic cropping.
2) Document scan in iOS with gallery image scanning.
3) Custom cropping of documents in iOS with camera scanning.

**Comment by ASDdgomez** [comment]
Hi,
in iOS : When push getDocument() , shows the photo taking screen, 1 second later closes the application, showing the message

**Comment by ASDdgomez** [comment]
Hi,
With this configuration, is working in iOS,
Thanks
