### ISSUE TITLE
i get error when i use flutter_doc_scanner with permission_handler 

### ISSUE THREAD

**Issue by abd1997-coder** [shirsh94/flutter_doc_scanner#5]
D/AndroidRuntime(13159): Shutting down VM
E/AndroidRuntime(13159): FATAL EXCEPTION: main
E/AndroidRuntime(13159): Process: com.vroad.athek, PID: 13159
E/AndroidRuntime(13159): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=213, result=-1, data=Intent { (has extras) 
}} to activity {com.vroad.athek/com.vroad.athek.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference

**Comment by shirsh94** [comment]
Hi @abd1997-coder ,

I've updated flutter_doc_scanner to version 0.0.7 to fix the issue with permission_handler. I've also updated my Android code accordingly. Thank you for bringing this to my attention.
