### ISSUE TITLE
when i use image_picker i get this error 

### ISSUE THREAD

**Issue by abd1997-coder** [shirsh94/flutter_doc_scanner#7]
kotlin.UninitializedPropertyAccessException: lateinit property resultChannel has not been initialized
E/AndroidRuntime(17495):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5230)
E/AndroidRuntime(17495):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5271)
E/AndroidRuntime(17495):        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(17495):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(17495):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(17495):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
E/AndroidRuntime(17495):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(17495):        at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(17495):        at android.app.ActivityThread.main(ActivityThread.java:7948)
E/AndroidRuntime(17495):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17495):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(17495):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/AndroidRuntime(17495): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property resultChannel has not been initialized
E/AndroidRuntime(17495):        at com.shirsh.flutter_doc_scanner.FlutterDocScannerPlugin.onActivityResult(FlutterDocScannerPlugin.kt:159)
E/AndroidRuntime(17495):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutE/AndroidRuntime(17495):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:422)
E/AndroidRuntime(17495):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:857)
E/AndroidRuntime(17495):        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:884)
E/AndroidRuntime(17495):        at android.app.Activity.dispatchActivityResult(Activity.java:8292)
E/AndroidRuntime(17495):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5223)
E/AndroidRuntime(17495):        ... 11 more

**Comment by shirsh94** [comment]
Thank you for raising the issue. It seems like error  with image_picker has been resolved in version 0.0.7 of the plugin. I recommend updating to the latest version to resolve this problem. If you encounter any further issues or have any questions, please feel free to let me know.
